### ISSUE TITLE
Scale Up DevOps Instance on Sep 10, 2019

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#69]
Wallet processes are consuming too much system resouce on Devops instance.

Need to upgrade the instance to m5a.

**Comment by AndyBoWu** [comment]
From t3.medium (2 vCPU, 4 GB) to m5a.large(2 vCPU, 8 GiB)

**Comment by LeoHChen** [comment]
when you launch a new instance of devop machine, make sure you associate
the original elastic IP to it, so that the DNS will keep working.
-----
Leo Chen

work hard, dream big, make history.
culture <https://harmony.one/culture>, team <https://harmony.one/team/>,
deck <https://harmony.one/deck>, roadmap <http://harmony.one/roadmap>,
vision <https://harmony.one/xoogler>, research
<https://harmony.one/research>, whitepaper <https://harmony.one/whitepaper>,
code <https://github.com/harmony-one/harmony>, annual-letter
<https://harmony.one/annual-letter>, newsletter <https://harmony.one/news>,
overview <http://harmony.one/overview>, binance-report
<https://harmony.one/binance-report>

**Comment by AndyBoWu** [comment]
done, but forgot to check if this instance has EIP attached or not. Lesson learned.
